language: c
compiler:
  - gcc

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev

before_install: ./.travis/prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - TESTSUITE=1 KERNEL=3.10.96


script: ./.travis/build.sh $OPTS

notifications:
  email:
    recipients:
      - ovs-build@openvswitch.org
